# Generated by Django 5.1.2 on 2024-11-07 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0002_alter_exerciseset_workout_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutplan',
            name='sessions',
            field=models.ManyToManyField(blank=True, null=True, related_name='workoutplans', to='workout.session'),
        ),
    ]
