# Generated by Django 5.1.2 on 2024-11-07 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0003_workoutplan_sessions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutplan',
            name='exercises',
            field=models.ManyToManyField(related_name='workoutplans', to='workout.exercise'),
        ),
    ]
